### ISSUE TITLE
Do mutexes work across isolates?

### ISSUE THREAD

**Issue by RickPoleshuck** [hoylen/dart-mutex#10]
The documentation should be changed to answer this question.?

**Comment by hoylen** [comment]
Ok, I'll consider adding a note about it in the next release.

But if you try to use a mutex across isolates, you should quickly realise it is impossible. The only way to communicate between isolates is to use the `Isolate.send()` method that only sends messages, so there is no way to refer to the same mutex in two different isolates. And the [isolates documentation](https://dart.dev/guides/language/concurrency#how-isolates-work) says they are designed so _you don't have to worry about mutexes or locks_.
