### ISSUE TITLE
Simple mutex use case not working

### ISSUE THREAD

**Issue by kbokarius** [hoylen/dart-mutex#4]
We've been debugging an issue and have discovered that the mutex isn't working. The mutex is able to `.acquire()` even though `isLocked == true`.

```
static Mutex mutex = new Mutex();

static testMutex() async {
  mutex.acquire();
  print("Acquired mutex");
  try {
     await Future.delayed(Duration(seconds: 1));
  } finally {
    mutex.release();
    print("Released mutex");
  }
}
```

Running the testMutex() method results in:

```
Acquired Mutex
Acquired Mutex
Acquired Mutex
Acquired Mutex
Released mutex
Released mutex
Released mutex
Released mutex
```

The Mutex isn't causing subsequent acquire() calls to block as expected. We're testing on iOS 13.7 using an iPhone 8 simulator.

**Comment by kbokarius** [comment]
Disregard, I realized we were missing an await before the acquire, my mistake.

**Comment by hoylen** [comment]
If you aren't using it already, the [Linter for Dart](https://dart-lang.github.io/linter/lints/) is very useful for detecting missing `await`.

In particular, the [unawaited_futures](https://dart-lang.github.io/linter/lints/unawaited_futures.html) rule.
